export const ref = Symbol('ref')
export const call = Symbol('call')
export const awaitSymbol = Symbol('await')
export const then = Symbol('then')
export const referenceSymbol = Symbol('referenceSymbol')
